global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using Microsoft.SqlServer.Management.Common;
global using System.Data.SqlClient;
global using Dapper;
global using Microsoft.VisualBasic.FileIO;
global using OptixTechnicalTest.Domain;
global using Microsoft.Extensions.Options;
global using OptixTechnicalTest.Helpers;
global using OptixTechnicalTest.Integration.Tests.Utilities;